# Poemas de Amor

Al fondo
de la catacumba de una noche velada,
vi el ícono Bizantino de tu rostro tendido
en el rubor de llamas.

En mi cama quedó la huella del sueño
de testigo de que subí de nuevo
de la cueva alumbrada,
pero aún en el ardor
de mi vientre se distingue

las facciones de tu cara, del rostro divino,
y como en la mortaja de Verónica,
del dolor infinito.

 

II.

Tus labios son del mismo color de la penumbra del crepúsculo,
e igual de lejos,
y mi ilusión tan falsa como el rumor de mar
del caracol hondo, entre las ondas del mar,
las ondas del mar, de fondo.

Luego escribo mis versos, y es como si subiera el caracol del mar
a besarme sobre el oído, y sobre el horizonte
el mar y el cielo
aprietan como si fueran tus labios, y se ponen del mismo color, 
como si fueran a darme no el anochecer sino el largo beso de buenas noches.

Luego escribo mis versos, y es como si subiera el caracol del mar
a besarme sobre el oído, y sobre mi cama
el despertar y el sueño
aprietan como dos labios, porque no fueron tus labios
sino el mar y el cielo, y un besito no mas de consuelo.

Luego subo el caracol a mi oído, y es como si escribiera mis versos
en el iluso delirio, y sobre la calle tu memoria
y tu ausencia aprietan como si fueran dos labios,
y me hacen de nuevo el largo beso de nada que hacer.

El caracol tiene tus mismos labios de penumbra morada,
y susurra el rumor, igual de falso,
de un mar lejano, entre el hondo rumor
de las ondas del mar,
las ondas del mar, de fondo.

Tus labios tienen el mismo rubor
Y susurran el mismo rumor


Quizás un día me iré de monje
a quedarme quieto un largo rato,
y me buscarás en aras de cariño,
pero de mi no habrá mas que una brisa tibia,
los narcisos, y una voz del hondo delirio:
No asustes, mi amor, que estoy aquí.

El reposo se funde en el frenesí,
la verdad en la fantasía,
y el amor en la demencia.

Pero no miras tanto a la verdad, mi amor.
Mirarme, mejor, a mi.



V.

Las feas torres y alambres de la ciudad
ya no son sino tu ventana.

Cruzo la calle con la mirada en alto,
sabiendo que asomará, en algún momento, tu cara.

Moro un rato en el pasillo de fondo-
presentirás una presencia a espaldas,

y al otro instante

habrá mi mano
en la calle aduraznado de tu vientre.

Tus labios buscarán el aire como cuando
Tomaron la hostia
y habrá mi susurro en tu oído:
no asustes, mi amor, que estoy aqui-

en el cielo triste y gris
que ya no es sino nuestro infinito reposo.


Para Brenda-

Las feas torres y alambres de la ciudad
ya no son sino tu ventana.
 
Cruzo la calle abajo con la mirada arriba,
sabiendo que asomará el ícono Bizantino de tu cara
tendida en el rubor de la catacumba
de alguna noche velada.

Y aprovecho,
tu con la mirada atenta en la calle abajo,
para hacerme arriba, tan arriba
como el cielo entero,
(para que volaras a mis brazos, ave de paraiso, en cuanto querias volar de mi)
a morar un rato en tu pasillo de fondo-

Y tu, con la mirada atenta calle abajo,
presentirás algo detras,
y al otro instante
 
habrá mi mano
en la calle aduraznado de tu vientre.
Tus labios buscarán el aire como cuando

buscaron la hostia
y habrá mi susurro en tu oído:
No asustes, mi amor, que estoy aqui-

Si se quien soy, ahora quiero que sepas quien eres tu.




VI.

A ti te gusta la danza,
y a mi que me gusta es el sueño.
En mi niñez dormía debajo un techo
tejido por tus pies que marcaban el paso,
tus pies que pisaban el techo,
el techo que tejaba el ritmo,
y el ritmo que marcaba mi sueño.

¡Qué harían mis techos de sueño sin tus pies
que tejaban el paso del ritmo!

Tus pies marcaban el paso
que iba tejando el ritmo
que marcaba mi techo,
el techo que también es mi sueño.

¡Qué harían mis techos de sueño sin tus pies
que tejaban el paso del ritmo!

Y supongo que tus pies sin mis techos
caerían al infierno.

 

VII.

¿Recuerdas, mi amor? el día que nevó aquí,
aquí en el pleno trópico?
Y el horizonte se borró,
Y una mano hecho de viento
Nos impulsaba hacia el infinito vértigo?




De niño subía al techo como diadema
que sube al frente del cacique
Quiché, a volverme tremendo,
tan tremendo como el cielo entero,
para que volaras a mis brazos, ave de paraíso,
en cuanto querrías volar de mi.





VIII.

Tu cuerpo es el palacio en la cimera de Sumeru
donde habitan las diosas del infinito cielo,
noventa y dos trillones en numero,
reposadas en sus cámaras de cortinas de seda,
sus cuerpos adornados de hilos de perlas
y amatistas y zafiros que brillan como brillaba
la miel de tus ojos en el frenesí.

Y soy fiel a su sagrado anhelo:
Voy de cámara a cámara de este palacio del cielo
a calmar el ardor de su celo,
noventa y dos trillones en numero,
con la mirada solemne,
como acólito que va de vela a vela,
callando las llamas con su pabilo,
y cada diosa me mira con los ojos en el frenesí,
ojos que dicen así:

Mi cuerpo es el palacio en la cimera de Sumeru
donde habitan las diosas del infinito cielo,
noventa y dos trillones en numero,
reposadas sobre sus sables y sedas celestiales,
en cámaras adornadas de zafiros, opales y amatistas que brillan
como brilla la miel de mis ojos en el frenesí.

Y soy fiel a tu sagrado anhelo.





IX.

Es el último poema.  No habrá otro poema
después, tratando de disimular las atrevidas avanzas que hice

sobre tu cuerpo, pues no hay palabra que no es mi mano,
y no hay hoja de papel que no sea lo alto brocado de tu muslo.

Mi solo anhelo era confesar, pero en mi confesión
salí más verdugo que en mi mismo pecado de anhelar.

Y aunque no seas quien yo pensaba haber visto al fondo
de las catacumbas veladas de mi delirio,

y aunque el anhelo que canto te parezca de papel y tinto,
no me importa-en mi intemperie de versos he captado

la cara más velada,
y mas real de que las realidades tuyas mal concebidas.
