# The Last Poem

One looks up and has the broken look-
The spires of gazes no longer sustain the sky,
the peasant peeping out from behind the furrow of brow,
The age not closing but writhing back on itself.
And stomach turned to face when the circle closed,
And face poured into stomach:
At the end of the age that struggled to close,
Stomach turns to face, and eyes to stomach,
And the eyes find on their face the kiss of the stomach
And the gentle caress is as tender as when
...

It seems like the sky of another planet.
And it's true, it's the sky of an imaginary world,
At the roof of their gaze, we project the sun of a day
That still has not ended.
...prefer the scathing weight, to the helium feet of the apogee.

And as with one face my stomach and I turn and say,
And the teeming columns of sky,
Everything is ready for the age to close,
Everything is at rest, but our gaze strikes the dirt
And the cloud of dust that starts up from the heathen earth
Takes on the aspect of a sputtering voice

There's no end to this morbid explaining
I'll just go on and on with a simple mooing.
We'll push aside all the cadaverous hands, if need be,
That our gaze won't dispel from the tops of our hands,
That reach for the new garment
At the backs of the darkest closets.



Midday arrived, I was in the milieu.
How strange to look upon myself
from above, and tell myself
From the crowd...

I stood there for some time,
the papers I swept off the table,
sifting from side to side,
not coming to rest,
and looking less and less
like a poem, and more like a rocket ship plan.

My fingers, like fir needles, opened and spread...
5...4...3...2...1...


...ascending the balconies of air...trying their hardest not to be a trapeze artist...

The cattle of time, giving us their backside
and grazing in the farthest corner of the pasture,
Whole days and weeks, months,
Silly bastards! It never even occurred to them
That they were supposed to be somewhere!
And when you tried to explain your justified rage,
they turned and gave up such a raucous moo-right in your face-
It shook you to the core, you walked around trembling for days.




*


Shaking his head, disbelieving his gall:
At the top of my voice there is something so strange,
It makes everyone flee the auditorium hall.
Listen, I'll tell you:
At the top of my voice,
I found something so strange:
Two eyes that witness the same strange things,
And two eyes that see the dream is bad,
But Listen: it's just a bad dream.

The mountains of Bogotá looked right down and saw through me,
I looked down at my chest and saw through me too:
In San Vincente, they were hunkering down for a patriotic night.
Or no, it's that-with the line of sight,
I'd mistaken the dignitaries and union panel
For my own liver and pituitary;
My stomach was there too,
And in no less of a hurry to take a decision.

The mountain looked down from a crest of sunlight,
I lifted my eyes to the back of my face,
And there was no mistaking the meaning in our brows:

I had to rise at the hour of the pueblo,
With the eyes of the roofs of the pueblo
Does the farmer look up and catch the first rays.
Like this we'd do too,
We'd have a good look at the earth we'd toiled,
My organs and I, and take a step out
Out over the earth,

The first step-uneven, that's how it is,
Because it feels for a moment like we'll no longer exist. [climb the balconies of night, trying our hardest/ not to be a trapeze artist]
We hear a strange story from a distant source
Of the strange distant people who walked out over the earth.

In hindsight, it didn't take much,
To lift our heads above the edge of the verse


The age not closing but writhing back on itself.
And stomach turned to face when the circle closed,
And face poured into stomach: the brimming toast
Mayakovsky had made on that day 
At the end of the age that struggled to close,
Stomach turns to face, and eyes to stomach,
And the eyes find on their face the kiss of the stomach
And the gentle caress is as tender as when
The first ray of light struck the first brow of mountain
And as with one face my stomach and I turn and say,
And the teeming columns of sky,
"What a strange way for the gold age to behave
No one will deny that the noontime sun
Is composed of helium, but it weighs on our necks
With the weight of the illusion our eyes refuse to dispell
At the hour of midday it's impossible to say
That x ever ended.
Everything is ready for the age to close,
Everything is at rest, but our gaze strikes the dirt
And the cloud of dust that starts up from the heathen earth
Takes on the aspect of a sputtering voice
There's just one more thing left to put to rest, but how to explain,
That a sky full of air won't tumble and fall?
There's no end to this morbid explaining
Nothing's happened at all.
I'll just go on and on with a simple mooing.
We'll push aside all the cadaverous hands, if need be,
That our gaze won't dispel from the tops of our hands,
That reach for the new garment
At the backs of the darkest closets.

Though none will deny that it's helium
That makes up the noonday sun,
One can't ignore the scathing weight
At the midday hour,
One looks up and has the broken look-
The spires of gazes no longer sustain the sky,
The peasant looks up from the furrow and sees
Not the life-giving sky, but a terrible cluster
Of bomblets.
It seems like the sky of another planet.
And it's true, it's the sky of an imaginary world,
At the roof of their gaze, we project the sun of a day
That still has not ended.
Still one prefers the imaginary weight,
To the weight of what had come true.






























Listen!

My words- there was a rumor
they were written already.

A voice spoke up from among the downturned pyramids:
This voice like a spire erupting from the throat,
Already you could hear them mumbling:
"What an old tyme shape, how quaint and forgotten."
And their questions could find no company
but themselves for an answer.

The train cars trickled into the vanishing twilight
With the weight of vermillion descending the distance.
Where was I anyway?  The Bolshoi Theater
On July eighteenth?  But no, this train
From Moscow to the Urals was a more likely guess,
My opening hand consulted,
Prague, Bogotá, Gaborone.

A voice was speaking up.  It said: Nothing:
Just so you know, just reporting, flew these rumors
Like soft cakes of dung, or dead leaves,
Or rotten parchments disintegrating in the casual breezes
Beneath the skeleton white of the poet's grin:

"What's recorded below's so
you'll know what was meant, but know
that in fact it were not words,
but divots of air
their absences left
that said what was there;
And when you looked closely, there's not even that."

If you watch how the train cars trail off there, you might catch something of how
I was on none of them.  With the weight of blood they descend the distance.

A coin!  A fruit!
A true-loined flute!
Dragged behind him the slow dirge of a tail.

When others came upon this serpent scrawl
In the sand, scrawling out an eternal s;
When these others came, who thought their tails proud,
The Hades Paparazzi, they insisted there was an outside
Observer, connected by an invisible appendage
Dictating all the things I said.  Were they right?-
A menacing stranger detached from me,
But for an eternal wormhook sinew?  Their Master, they hinted.
"Well then," I replied to the flashing bulbs,
"I knew I had to overcome something."
O, the Anger stewing!
At the other end of that long tunnel!
Their distaste they expressed by vanishing
enigmatically; and a wind rushed in to fill the new emptiness.

Envoi

Announcement I saw on the mornings of May:
"We can no longer raise our skulls into space
Like goblets of wine, in toast to the place.
At the midday hour there's a break in our spine.

So there'll be no more of that backbone flute."
This I saw posted again on the walls of midday.
But we preferred instead the scathing weight
of a day that didn't end,
	To the weight of what had come true.






















.1.

Hours later, I was outwardly calm at last; I wandered out onto the rocket pad
(there's a time of evening when launch pads revert to their pastoral natures).

Anyway it was an easy problem to solve, I considered,
From the very beginning-who was it who said:
"The whole bourgeois world is bleeding from the hole
In Mayakovsky's head?"

No one?  No one had yet said it then-but it had been known-
Though the staves of peasants and Baltic ice
were the first to frame it in a delicate way-
But the primordial news was something one'd heard,
In the thunder-tread of the dinosaurs.
A similar thought must have passed through Gagarin's head
As it lay reclined 160 degrees against the arc of the rocket blast-
The better to take in the deep starry draught
Of the starry brew-Armstrong went up in search of his wife's
New shoes.
Gagarin went up in search of the news.

10.9.8.

But hey!  What's that!  Grab the binoculars!
A figure running out onto the rocketpad!
It's Voznesensky!  Christ!

What's he doing?

At the last minute Voznesensky had broken through
The barriers, and was racing out onto the rocketpad,
Waving a bundle of papers in his flickering hand.

He'll be roasted alive!

Though from our angle you couldn't tell what he meant,
You saw in his hand the full-blooded ferment:
Come back!  I have a quicker-!

But it was too late.
Voznysensky and his poems were swept up,
In the warm embrace of the rocket blast.
All of the Gosplan turned their ear to the sky
And made a big show of hearing the news,
But even Gagarin was disappointed with the view.
"All you get to see," (the suppressed transcript reads)
"Is Armstrong go shopping for his wife's new shoes."

Hours later, I wandered out onto the rocket pad, outwardly calm
(there's a time of evening when the launch pads revert to their pastoral natures),

I marveled and pondered:
So what was it that Voznesensky meant?
Earlier that morning, I'd wiped the pages from my desk
And went out for a walk.
I saw Voznysensky stand there in the forest,
And watch the spring breeze get lodged in the branches,

5.4.3.2.

Slowly, his fingers, like fir needles, opened and spread.

.1.

It's not blood that bleeds from Mayakovsky's head.

Envoi

In the official version they'll say it's inane
For poets to run out onto rocket pads
And be swept away by tongues of rocket flame
But when I returned the pages still
Sailed to the floor.
And I'd say I've deciphered the way
To decipher the words that were emblazoned
On the breast of the air that day.

It's the disarray and the hopeless moment
That lifts its head to the back of its face
And rises up and speaks.
Can it be that it's the tongue of flame
That's native to all?
The flickering edges of disorganized papers
Are not unlike the footsure steps of a midnight interloper
Nor too unlike Voznysensky's lips:
It's the rose red flame of one's own flickering gaze
That has kept them in motion.

(It's that sort of thing one starts to see,
By not fleeing the auditorium
On April 14th)

	And while I said this to my friends,
My stomach in tandem had turned and said
	a nobler speech:

"It's a feeling deep in the stomach, my friends,
It makes the stomach turn and say,
'True, our spine's a ladder to the top of the sky,
But since that day, we can no longer do
What Bolshevik posters ask us to.
Lift our skulls to the top of our voice?
Brother, we'll be lucky if we can lift our heads
From the back of the pew.'"






























A Reflection

It wakes us with a start-how long did we sleep?
How long ago did we doze off without knowing?
It speaks to us from a long way off,
An Octobrist poster
Peeling from the walls of the station,
A sigh, and reflection:
The farthest distance is October to May.

It had been such a long time since anyone stood
At the center of the day,
One hardly recognizes the place-one staggers and says:
It's been such a long time since it was easy to make
A connection between
The place we're in and the time of day.

It's the same bad dream gives its locks a shake.
It's a feeling deep in the stomach;
It makes the stomach turn and say:
"We went along with life as long as we knew
There were certain things too inane to be true."
But the cosmos of things that do us offense
Foreseen in our dreams as we sleep out in the open
On the Jianganshan, and or the windowpanes
Rattle outside of Seville.

In those dreams, we see the old face,
Gives his powdered locks a shake
And rushes to our aid, but who-
Is it Grandpa?-Ah, no, it's God!
And it's we who're rushing towards him!
Cutting through the dark fumes,
We smear our lips on his weeping hand
And say: No, please, don't let there be Rand
Corp., don't let it be true
That there's anything so strange as saks
Fifth avenue, nor pinochet, nor, above all,
That winnowed look on Moscow faces,
Nor other things not mentioned in Das Kapital.

Not God, then, but the dream turns its head:
Though the objects of twilight will show their teeth
In a terrible way, don't let the mingling
Of the predawn shadows
Deter your hands from the warm embrace.

Emancipation, huh!
And indeed the next day, as we marched out in formation,
Our chests were full with the brimming sound
And again and again, our stomping feet measured out
The words we had heard in our sleep.




Envoi

Whatever the [auditorium of the brain] is for you,
Whether your beloved form up the arching walls,
And you bask in the glow of their sharded light
That falls through their bellies.
Or whether echoes of curses and breaking glass
Lay down in your mind like halls of stained glass.
Or the leafy corridors of country roads resound
With the brimming resonance of a low organ pipe,
It's a place so lucid you see,
Never again were our lampoons so lucid
That posters could hang on the rays of the sun.
We begin to remember.but Listen!
Will it do us any good?  Are we good at remembering?]

Envoi

Well, everyone wondered what I should call it,
And we never did figure out what it was,
And tidal waves distantly mounted and sang to us!
But who was it kept saying?  Ben,
Call it this and call it that!
And going back and forth like this,

How funny how long we could stay in the air,
Even though we tried our hardest
Not to be a trapeze artist.

While others sought the sea floor.
Still others did not exist; I had lied
Just to flesh things out-
And this in turn gave us the problem
We had come to solve.

At last I was going to speak
When I realized my lips had set sail
How many eons ago!  Oh,

But one word was left, ascending the balconies
Of air-and aptly spoken-footsure
As a midnight interloper
But caught in the heart of day.

We see it edge-on,
It's written on those papers of mine
that swirl to the floor.

Just now did I see they'd not come to rest,
I'm almost thirty now-it was long ago
When I wiped them from my desk.

What was the hand, before I was born,
That had swept them in disgust
from the drafting board?


Envoi

Anyways, I don't know how long it was
I thought I was seated there
Locked in the stares of the empty chairs.
(Was it in the castle of Prague?)
At that strange table made not of wood
But of the sifting fingers and twelfth night fog,
Sifting our bodies into a thousand small grains
(Or even some higher number we'd not yet thought of,)
The shoreline stooped down, and soaked the brocade
Of her skirts,
And scooped up in her hand a handful of dirt,
My eyes, like two marbles, rolled from the page
And fell into the sea-plop!  Plop!
The strangest thing I'd seen up until then,
Were her skirts made of chalk.

The sands sifted and fell
And I was well
On my way to sleep,
When they sifted and welled to the bottom of the sea.

The characters of the world I then looked out upon,
Were the unconscious sands that slipped through her fingers,
With names like Christ.
And the spires of the city-voices so ambient and strange
That they made not a sound, and yet chose still to speak:



And Yet.

In those days the seconds ticked away with a machine
Gun rattle.  

All day long one puts up a show of resistance
To the end of the day.  Careful-it's a dirty way
To make the effort that's needed
To bring a close to the day that began in 1930.
Usually I just go to sleep,
When I see the trouble that's coming at noon.
It's such a large effort just to think
Up the imaginary weight.
Of another day,
When one knows all too well
That the days haven't ended
Since April 14th.

On June 9, 1999, I landed in La Habana, Cuba
To attend the 11th Annual Philosophers' and Social Scientists' Conference.
[My ankles wore little cloaks of fume,]
[I looked through the gray hue]
I saw from the sea to the tippy-top of the sky,
Where the sun would soon be,
To the very bottom of the sea.
I'd not known it, but the stairs I climbed to get into the plane,
Were actually my spine,
And my head was the Cuban sun:
I'd come to stand at the top of my voice.
I walked down my tongue
Out into the sky.

I mention it because it might be of some use
In deducing the way that those strange years passed.
But youth, what a thing!  What a starless ordeal!
First 2000 arrived, then 2001.
No one said that 2002 would ever come.
Then the same was said of 2003.

Well, it went on like this until I turned 30.
I am trying to build a word fast enough
To get around it all.

Time behaved like 
Nothing was the same after that.
New questions were turned up in the soil.
It meant not God
But the whole cosmos was turning its head...

Our new souls were still hanging there in the back of the closet
But no one had yet dared to try on the garment.

